config/routes.rb
MeatApp2::Application.routes.draw do
  root :to => 'sessions#new'
  resources :users do
    resources :companies, :only => [:show]
  end
  
  resources :companies do 
    resources :suppliers
    resources :deliveries, :only => [:index]
    resources :inventories, :orders do
      collection do
        get 'supplier_list'
      end
    end
  end

  resources :suppliers, :only => :none do
    resources :products
    resources :order_days
    resources :inventories, :orders do
      collection do
        put 'update_supplier_line'
      end
    end
  end

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signout' => 'sessions#destroy'
end

app/models/inventory.rb
include ApplicationHelper

class Inventory < ActiveRecord::Base
  attr_accessible :company_id, :date_string, :product_id, :quantity, :supplier_id, :quantity

  belongs_to :company
  belongs_to :supplier
  belongs_to :product

  before_save :set_date

  def set_date
    date_formatted(Time.now) if !date_string
  end

  def self.update_from_inventory_form(form_hash)
    form_hash.each do |inventory_id, quantity|
    inventory = self.find(inventory_id)
    inventory.update_attributes(quantity)
    end
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @supplier = Supplier.find(params[:supplier_id])
    @company = @supplier.company
    @inventories = @supplier.get_or_create_todays_suppliers_inventories
    @notices = params[:notices] if params[:notices]
    @page_header = "Inventory for #{@supplier.name}"
  end

  def supplier_list
    @company = Company.find(params[:company_id])
    @suppliers = @company.suppliers
    @notices = params[:notices] if params[:notices]
    @page_header = "Take Inventory"
  end

  def update_supplier_line
    supplier = Supplier.find(params[:supplier_id])
    company = supplier.company
    if Inventory.update_from_inventory_form(params[:inventory])
      redirect_to supplier_list_company_inventories_path(company, :notices => [Messages.inventory_success(supplier)])
    else
      redirect_to supplier_inventories_path(supplier, :errors => [:inventory => Messages.inventory_fail])
    end
  end
end

app/views/inventories/index.html.erb
<%= form_tag update_supplier_line_supplier_inventories_path(@supplier), :method => :put, :class => 'inventory_form' do %>
  <table>
    <thead>
      <th>Product</th>
      <th>Quantity</th>
    </thead>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.product.name %></td>
        <%= fields_for 'inventory[]', inventory do |inventory_form| %>
          <td><%= inventory_form.text_field "quantity", :type => 'number', :min => 0 %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= submit_tag 'Save Inventory', :class => 'button' %>
<% end %>

app/views/inventories/supplier_list.html.erb
<% @suppliers.each do |supplier| %>
  <%= link_to supplier.name, supplier_inventories_path(supplier), :class => 'small button expand' %>
<% end %>