config/routes.rb
MeatApp2::Application.routes.draw do
  root :to => 'sessions#new'
  resources :users do
    resources :companies, :only => [:show]
  end
  
  resources :companies do 
    resources :suppliers
    resources :deliveries, :only => [:index]
    resources :inventories, :orders do
      collection do
        get 'supplier_list'
      end
    end
  end

  resources :suppliers, :only => :none do
    resources :products
    resources :order_days
    resources :inventories, :orders do
      collection do
        put 'update_supplier_line'
      end
    end
  end

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signout' => 'sessions#destroy'
end

app/models/order_day.rb
class OrderDay < ActiveRecord::Base
  attr_accessible :day, :duration, :supplier_id
  validates :duration, :numericality => {:message => "Duration must be a number"}
  belongs_to :supplier
end

app/controllers/order_days_controller.rb
class OrderDaysController < ApplicationController
  def new
    @order_day = OrderDay.new
    @supplier = Supplier.find(params[:supplier_id])
    @days_of_week = days_of_week_options_array
    @page_header = 'Add Order / Delivery Days'
    @errors = params[:errors][:order_day] if params[:errors]
  end

  def create
    order_day = OrderDay.new(params[:order_day])
    supplier = Supplier.find(params[:supplier_id])
    company = supplier.company
    if order_day.save
      supplier.order_days << order_day
      redirect_to edit_company_supplier_path(company, supplier)
    else
      redirect_to new_supplier_order_day_path(supplier, :errors => {:order_day => order_day.errors.messages})
    end
  end

  def edit
    @order_day = OrderDay.find(params[:id])
    @supplier = Supplier.find(params[:supplier_id])
    @days_of_week = days_of_week_options_array
    @errors = params[:errors][:order_day] if params[:errors]
  end

  def update
    supplier = Supplier.find(params[:supplier_id])
    company = supplier.company
    order_day = OrderDay.find(params[:id])
    if order_day.update_attributes(params[:order_day])
      redirect_to edit_company_supplier_path(company, supplier)
    else
      redirect_to edit_supplier_order_day_path(supplier, order_day, :errors => {:order_day => order_day.errors.messages})
    end
  end

  def destroy
    order_day = OrderDay.find(params[:id])
    supplier = Supplier.find(params[:supplier_id])
    company = supplier.company
    if order_day.destroy
      redirect_to edit_company_supplier_path(company, supplier)
    else 

    end
  end
end

app/views/order_days/edit.html.erb
<h1>Edit Order / Delivery Days</h1>
<%= form_for @order_day, :url => supplier_order_day_path(@supplier, @order_day), :method => :put do |f| %>
  <label for 'day'>Order Day</label>
  <%= f.select("day", @days_of_week, :selected => "monday") %>
  <label for 'day'>Delivery Day</label>
  <%= f.text_field 'duration', :placeholder => '(ex: mon - wed is "2" days)', :class => 'small-9', :type => 'number', :min => 0 %>
  <%= f.submit 'update order delivery day', :class => 'button' %>
<% end %>

app/views/order_days/new.html.erb
<%= form_for @order_day, :url => supplier_order_days_path(@supplier) do |f| %>
  <label for 'day'>Order Day</label>
  <%= f.select("day", @days_of_week, :selected => "monday") %>
  <label for 'day'>Delivery Day</label>
  <%= f.text_field 'duration', :placeholder => '(ex: mon - wed is "2" days)', :class => 'small-9', :type => 'number', :min => 0 %>
  <%= f.submit 'save order delivery day', :class => 'button' %>
<% end %>