config/routes.rb
MeatApp2::Application.routes.draw do
  root :to => 'sessions#new'
  resources :users do
    resources :companies, :only => [:show]
  end
  
  resources :companies do 
    resources :suppliers
    resources :deliveries, :only => [:index]
    resources :inventories, :orders do
      collection do
        get 'supplier_list'
      end
    end
  end

  resources :suppliers, :only => :none do
    resources :products
    resources :order_days
    resources :inventories, :orders do
      collection do
        put 'update_supplier_line'
      end
    end
  end

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signout' => 'sessions#destroy'
end

app/models/supplier.rb
include ApplicationHelper

class Supplier < ActiveRecord::Base
  attr_accessible :company_id, :name

  validates :name, :presence => {:message => 'Supplier must have a name'}

  belongs_to :company
  has_many :products
  has_many :order_days
  has_many :orders
  has_many :inventories

  def get_or_create_todays_suppliers_inventories
    inventories = []
    products.each do |product|
      inventory = Inventory.includes(:product).find_or_create_by_date_string_and_product_id(date_formatted(Time.now), product.id)
      self.inventories << inventory
      self.company.inventories << inventory
      product.inventories << inventory
      inventories << inventory
    end
    inventories
  end

  def get_or_create_todays_suppliers_orders
    orders = []
    products.each do |product|
      order = Order.includes(:product).find_or_create_by_order_date_string_and_product_id(date_formatted(Time.now), product.id)
      self.orders << order
      self.company.orders << order
      product.orders << order
      order.set_delivery_date
      orders << order
    end
    orders
  end

  def get_ordering_days
    order_days.map {|day| day.day }
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @company = Company.find(params[:company_id])
    @supplier = Supplier.new
    @page_header = 'Add New Supplier'
    @errors = params[:errors][:supplier] if params[:errors]
  end

  def create
    company = Company.find(params[:company_id])
    supplier = Supplier.new(params[:supplier])
    if supplier.save
      company.suppliers << supplier
      redirect_to edit_company_supplier_path(company, supplier)
    else  
      redirect_to new_company_supplier_path(company, :errors => {:supplier => supplier.errors.messages})
    end
  end

  def edit
    @company = Company.find(params[:company_id])
    @supplier = Supplier.find(params[:id])
    @products = @supplier.products
    @order_days = @supplier.order_days
    @page_header = "Update #{@supplier.name}"
    @errors = params[:errors][:product] if params[:errors]
  end

  def update
    company = Company.find(params[:company_id])
    supplier = Supplier.find(params[:id])
    if supplier.update_attributes(params[:supplier])
      redirect_to company_suppliers_path(company)
    else
      redirect_to edit_company_supplier_path(company, supplier, :errors => {:supplier => supplier.errors.messages})
    end
  end

  def index
    @company = Company.find(params[:company_id])
    @suppliers = @company.suppliers
    @page_header = "Manage Suppliers"
  end

  def show
    @company = Company.find(params[:company_id])
    @supplier = Supplier.find(params[:id])
    @products = @supplier.products
    @order_days = @supplier.order_days
    @page_header = @supplier.name
  end
end

app/views/suppliers/create.html.erb
<h1>Suppliers#create</h1>
<p>Find me in app/views/suppliers/create.html.erb</p>

app/views/suppliers/edit.html.erb
<%= form_for @supplier, :html => {:method => 'put'}, :url => company_supplier_path(@company, @supplier) do |f| %>
  <%= f.text_field 'name', :placeholder => 'Supplier Name' %>
  <%= f.submit 'Update Supplier Name', :class => 'button' %>
<% end %>

<%= link_to 'add new product', new_supplier_product_path(@supplier), :class => 'button' %>
<table id="products_table">
  <thead>
    <tr>
      <th colspan="100%">Products</th>
    </tr>
  </thead>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td>
          <%= link_to 'edit', edit_supplier_product_path(@supplier, product), :class => 'edit_btn' %>
          &nbsp | &nbsp
          <%= link_to 'delete', supplier_product_path(@supplier, product), :method => :delete, :class => 'delete_btn', :confirm => Messages.delete_product %>
        </td>
      </tr>
    <% end %>
</table>

<%= link_to 'add order / delivery day', new_supplier_order_day_path(@supplier), :class => 'button' %>
<table id="order_days_table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Duration</th>
      <th></th>
    </tr>
  </thead>
    <% @order_days.each do |order_day| %>
      <tr>
        <td><%= order_day.day %></td>
        <td><%= order_day.duration %></td>
        <td>
          <%= link_to 'edit', edit_supplier_order_day_path(@supplier, order_day), :class => 'edit_btn' %>
          &nbsp | &nbsp
          <%= link_to 'delete', supplier_order_day_path(@supplier, order_day), :method => :delete, :class => 'delete_btn' %>
        </td>
      </tr>
    <% end %>
</table>

app/views/suppliers/index.html.erb
<% @suppliers.each do |supplier| %>
  <%= link_to supplier.name, company_supplier_path(@company, supplier), :class => 'small button expand' %>
<% end %>
<%= link_to 'Add Supplier', new_company_supplier_path(@company), :class => 'button' %>

app/views/suppliers/new.html.erb
<%= form_for @supplier, :url => company_suppliers_path(@company) do |f| %>
  <%= f.text_field 'name', :placeholder => 'Supplier Name' %>
  <%= f.submit 'Add Supplier', :class => 'button' %>
<% end %>

app/views/suppliers/show.html.erb
<table>
  <thead>
    <tr>
      <th>Products</th>
    </tr>
  </thead>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
      </tr>
    <% end %>
</table>

<table>
  <thead>
    <tr>
      <th colspan="2">Order / Delivery Days</th>
    </tr>
  </thead>
    <% @order_days.each do |order_day| %>
      <tr>
        <td><%= order_day.day %></td>
        <td><%= order_day.duration %></td>
      </tr>
    <% end %>
</table>
<%= link_to "edit supplier", edit_company_supplier_path(@company, @supplier), :class => 'button' %>