config/routes.rb
MeatApp2::Application.routes.draw do
  root :to => 'sessions#new'
  resources :users do
    resources :companies, :only => [:show]
  end
  
  resources :companies do 
    resources :suppliers
    resources :deliveries, :only => [:index]
    resources :inventories, :orders do
      collection do
        get 'supplier_list'
      end
    end
  end

  resources :suppliers, :only => :none do
    resources :products
    resources :order_days
    resources :inventories, :orders do
      collection do
        put 'update_supplier_line'
      end
    end
  end

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signout' => 'sessions#destroy'
end

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to 'Meat App', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
     
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <% if current_user %>
        <li class="header-welcome-text">Hello <%= current_user.first_name %></li>
        <li class="divider"></li>
        <% if current_user.companies.count > 0 %>
          <li><%= link_to 'Suppliers', company_suppliers_path(current_user.companies.first) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Deliveries', company_deliveries_path(current_user.companies.first) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Take Inventory', supplier_list_company_inventories_path(current_user.companies.first) %></li>
          <li class="divider"></li>
          <li><%= link_to 'Place Orders', supplier_list_company_orders_path(current_user.companies.first) %></li>
          <li class="divider"></li>
        <% end %>
        <li><%= link_to 'Signout', signout_path %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign Up', signup_path %></li>
      <% end %>
    </ul>
  </section>
</nav>
<%= render :partial => 'shared/errors', :locals => {:errors => @errors} if @errors %>
<%= render :partial => 'shared/notices', :locals => {:notices => @notices} if @notices %>
<% if @page_header %>
  <h1 class="page_header"><%= @page_header %></h1>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render :partial => 'layouts/header' %>
  <div class="row">
    <div class="large-12 large-centered columns">
      <%= yield %>
    </div>
  </div>  
  <%= javascript_include_tag "application" %>
  </body>
</html>